# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

BSGDWrapper <- function(X, Y, C, budget, gamma, epochs, budgetMaintenanceStrategy, useBias = TRUE, verbose = FALSE) {
    .Call('RcppShark_BSGDWrapper', PACKAGE = 'RcppShark', X, Y, C, budget, gamma, epochs, budgetMaintenanceStrategy, useBias, verbose)
}

DeepNetworkWrapperTrain <- function(X, Y, nHidden1 = 8L, nHidden2 = 8L, unsupRegularisation = 0.001, noiseStrength = 0.3, unsupIterations = 100L, regularisation = 0.0001, iterations = 200L, verbose = FALSE) {
    .Call('RcppShark_DeepNetworkWrapperTrain', PACKAGE = 'RcppShark', X, Y, nHidden1, nHidden2, unsupRegularisation, noiseStrength, unsupIterations, regularisation, iterations, verbose)
}

DeepNetworkWrapperPredict <- function(X, Y, weights, nHidden1, nHidden2, inputSize, outputSize, verbose = FALSE) {
    .Call('RcppShark_DeepNetworkWrapperPredict', PACKAGE = 'RcppShark', X, Y, weights, nHidden1, nHidden2, inputSize, outputSize, verbose)
}

ELMWrapperTrain <- function(X, Y, nHidden, verbose = FALSE) {
    .Call('RcppShark_ELMWrapperTrain', PACKAGE = 'RcppShark', X, Y, nHidden, verbose)
}

ELMWrapperPredict <- function(X, Y, weights, normalizerWeights, nHidden, inputSize, outputSize, verbose = FALSE) {
    .Call('RcppShark_ELMWrapperPredict', PACKAGE = 'RcppShark', X, Y, weights, normalizerWeights, nHidden, inputSize, outputSize, verbose)
}

applyKMeansFromCSVFile <- function(filename) {
    invisible(.Call('RcppShark_applyKMeansFromCSVFile', PACKAGE = 'RcppShark', filename))
}

applyKMeans <- function(X) {
    .Call('RcppShark_applyKMeans', PACKAGE = 'RcppShark', X)
}

